module.exports = {
  'Famous Landmarks': 'Eiffel Tower,Big Ben,Statue of Liberty,Colosseum,Great Wall,Taj Mahal,Pyramids,Opera House,Stonehenge,Machu Picchu,Golden Gate,Mount Rushmore,Leaning Tower,Petra,Christ the Redeemer,Burj Khalifa',
  'Kitchen Items': 'Whisk,Colander,Toaster,Blender,Spatula,Ladle,Kettle,Rolling Pin,Grater,Tongs,Peeler,Frying Pan,Oven Mitt,Cutting Board,Mixer,Tea Towel',
  'Zoo Animals': 'Lion,Giraffe,Penguin,Elephant,Zebra,Monkey,Tiger,Hippo,Kangaroo,Panda,Flamingo,Gorilla,Rhino,Koala,Camel,Meerkat',
  'Sports': 'Soccer,Tennis,Rugby,Golf,Boxing,Cricket,Swimming,Archery,Surfing,Baseball,Hockey,Skiing,Cycling,Fencing,Netball,Darts',
  'Fruit and Veg': 'Apple,Banana,Carrot,Broccoli,Mango,Potato,Grape,Pumpkin,Lemon,Spinach,Strawberry,Onion,Pineapple,Corn,Cucumber,Peach',
  'Jobs': 'Teacher,Doctor,Pilot,Plumber,Chef,Farmer,Lawyer,Firefighter,Electrician,Dentist,Journalist,Builder,Nurse,Mechanic,Actor,Librarian',
  'Vehicles': 'Bicycle,Tram,Helicopter,Submarine,Tractor,Scooter,Ferry,Ambulance,Skateboard,Bus,Canoe,Motorbike,Truck,Hot Air Balloon,Train,Taxi',
  'Clothing': 'Jeans,Scarf,Sneakers,Raincoat,Hoodie,Bikini,Tuxedo,Beanie,Overalls,Socks,Kilt,Pyjamas,Sandals,Tie,Gloves,Apron',
  'Instruments': 'Guitar,Piano,Violin,Drums,Flute,Trumpet,Harp,Saxophone,Cello,Banjo,Tuba,Clarinet,Ukulele,Accordion,Bagpipes,Triangle',
  'Countries': 'Australia,Brazil,Egypt,Japan,Canada,Italy,India,Mexico,Norway,Kenya,Peru,Iceland,Greece,Thailand,Spain,Chile',
  'Board Games': 'Monopoly,Chess,Scrabble,Cluedo,Risk,Checkers,Jenga,Battleship,Catan,Twister,Trivial Pursuit,Backgammon,Uno,Pictionary,Operation,Connect Four',
  'Fast Food': 'Burger,Fries,Nuggets,Pizza,Hot Dog,Taco,Milkshake,Kebab,Onion Rings,Fish and Chips,Burrito,Sub,Wings,Donut,Wrap,Soft Serve',
  'Ocean Life': 'Shark,Dolphin,Octopus,Jellyfish,Whale,Seahorse,Crab,Starfish,Turtle,Stingray,Clownfish,Squid,Lobster,Eel,Coral,Seal',
  'Furniture': 'Sofa,Wardrobe,Bookshelf,Armchair,Desk,Bunk Bed,Coffee Table,Stool,Dresser,Rocking Chair,Bench,Ottoman,Cabinet,Hammock,Futon,Bean Bag',
  'Tools': 'Hammer,Screwdriver,Saw,Drill,Wrench,Pliers,Chisel,Spirit Level,Tape Measure,Axe,Shovel,Crowbar,Sandpaper,Ladder,Hacksaw,Paintbrush',
  'Body Parts': 'Elbow,Ankle,Knee,Shoulder,Wrist,Spine,Jaw,Thumb,Heel,Rib,Palm,Eyebrow,Neck,Hip,Chin,Toe',
  'Weather': 'Rain,Snow,Fog,Thunder,Hail,Tornado,Heatwave,Drizzle,Rainbow,Blizzard,Hurricane,Breeze,Frost,Monsoon,Lightning,Drought',
  'Sweets': 'Chocolate,Gummy Bears,Lollipop,Liquorice,Fudge,Marshmallow,Toffee,Jelly Beans,Candy Floss,Mints,Caramel,Sherbet,Nougat,Bubblegum,Truffle,Popcorn',
  'School Subjects': 'Maths,History,Art,Science,Geography,Music,PE,English,Drama,Chemistry,Physics,Biology,French,Woodwork,Computing,Economics',
  'Dog Breeds': 'Poodle,Labrador,Bulldog,Beagle,Pug,Husky,Dalmatian,Corgi,Greyhound,Chihuahua,Dachshund,Boxer,Collie,Rottweiler,Spaniel,Terrier',
  'World Cities': 'Paris,Tokyo,New York,Sydney,Cairo,Rome,London,Rio,Dubai,Moscow,Berlin,Mumbai,Toronto,Bangkok,Athens,Las Vegas',
  'Holidays': 'Christmas,Easter,Halloween,Diwali,Thanksgiving,New Year,Valentine\'s Day,Eid,Hanukkah,Birthday,Carnival,Mother\'s Day,Bonfire Night,Lunar New Year,Anzac Day,Fourth of July',
  'Music Genres': 'Rock,Jazz,Pop,Country,Hip Hop,Classical,Reggae,Metal,Punk,Disco,Blues,Opera,Techno,Folk,Soul,Funk',
  'Mythical Creatures': 'Dragon,Unicorn,Mermaid,Phoenix,Centaur,Vampire,Werewolf,Troll,Fairy,Zombie,Yeti,Kraken,Genie,Ghost,Goblin,Giant',
  'Hobbies': 'Knitting,Fishing,Gardening,Painting,Chess,Hiking,Baking,Photography,Pottery,Gaming,Camping,Yoga,Singing,Birdwatching,Origami,Skateboarding',
  'Toys': 'Lego,Teddy Bear,Yo-yo,Doll,Kite,Jigsaw,Rubik\'s Cube,Slinky,Marbles,Trampoline,Rocking Horse,Play-Doh,Frisbee,Water Gun,Spinning Top,Skipping Rope',
  'Breakfast Foods': 'Pancakes,Cereal,Toast,Bacon,Porridge,Croissant,Waffles,Omelette,Yoghurt,Muesli,Bagel,Sausage,Fried Egg,Crumpet,Smoothie,Hash Browns',
  'Bathroom': 'Toothbrush,Shower,Towel,Soap,Mirror,Bath,Shampoo,Razor,Plunger,Sponge,Toilet Paper,Bath Mat,Hairdryer,Scale,Sink,Loofah',
  'At the Beach': 'Sandcastle,Surfboard,Sunscreen,Seagull,Bucket,Umbrella,Snorkel,Deckchair,Seaweed,Lifeguard,Flip Flops,Ice Cream,Shell,Pier,Cooler,Boogie Board',
  'Drinks': 'Coffee,Tea,Lemonade,Beer,Wine,Cola,Milk,Orange Juice,Whisky,Champagne,Hot Chocolate,Cider,Water,Cocktail,Iced Tea,Espresso',
  'Dances': 'Waltz,Tango,Salsa,Ballet,Breakdance,Macarena,Tap,Foxtrot,Hula,Flamenco,Disco,Line Dance,Polka,Conga,Twist,Cha-Cha',
  'Camping': 'Tent,Sleeping Bag,Campfire,Torch,Compass,Backpack,Map,Stove,Lantern,Hiking Boots,Thermos,Pocket Knife,Tarp,Mosquito Net,Binoculars,Firewood',
  'Movie Genres': 'Horror,Comedy,Western,Romance,Thriller,Musical,Sci-Fi,Documentary,Animation,Action,Fantasy,Mystery,War,Crime,Drama,Heist',
  'Technology': 'Laptop,Smartphone,Drone,Printer,Headphones,Router,Camera,Smartwatch,Microwave,Robot,Keyboard,Satellite,Charger,Television,Console,Tablet',
  'Birds': 'Eagle,Owl,Parrot,Pelican,Sparrow,Crow,Swan,Peacock,Ostrich,Toucan,Hummingbird,Magpie,Duck,Kookaburra,Robin,Seagull',
  'Natural Wonders': 'Grand Canyon,Great Barrier Reef,Everest,Niagara Falls,Sahara,Amazon,Uluru,Victoria Falls,Northern Lights,Dead Sea,Volcano,Glacier,Geyser,Rainforest,Cave,Fjord',
};
